config/routes.rb
Rails.application.routes.draw do
  resources :utentis
  resources :users
  resources :tours
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/index', to: 'home#index', as: 'index'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tour.rb
class Tour < ApplicationRecord
    has_one_attached :cover
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/utenti.rb
class Utenti < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: %i[ show edit update destroy ]

  # GET /tours or /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1 or /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours or /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: "Tour was successfully created." }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1 or /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: "Tour was successfully updated." }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1 or /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: "Tour was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tour_params
      params.require(:tour).permit(:denominazione, :descrizione, :descrizioneing, :luogopartenza, :giorniorarip, :durata, :maxpartecipanti, :cover)
    end
end

app/controllers/utentis_controller.rb
class UtentisController < ApplicationController
  before_action :set_utenti, only: %i[ show edit update destroy ]

  # GET /utentis or /utentis.json
  def index
    @utentis = Utenti.all
  end

  # GET /utentis/1 or /utentis/1.json
  def show
  end

  # GET /utentis/new
  def new
    @utenti = Utenti.new
  end

  # GET /utentis/1/edit
  def edit
  end

  # POST /utentis or /utentis.json
  def create
    @utenti = Utenti.new(utenti_params)

    respond_to do |format|
      if @utenti.save
        format.html { redirect_to @utenti, notice: "Utenti was successfully created." }
        format.json { render :show, status: :created, location: @utenti }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @utenti.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /utentis/1 or /utentis/1.json
  def update
    respond_to do |format|
      if @utenti.update(utenti_params)
        format.html { redirect_to @utenti, notice: "Utenti was successfully updated." }
        format.json { render :show, status: :ok, location: @utenti }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @utenti.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /utentis/1 or /utentis/1.json
  def destroy
    @utenti.destroy
    respond_to do |format|
      format.html { redirect_to utentis_url, notice: "Utenti was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_utenti
      @utenti = Utenti.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def utenti_params
      params.require(:utenti).permit(:cognome, :nome, :indirizzo, :email, :numero, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/utentis_helper.rb
module UtentisHelper
end

app/views/home/index.htm.erb
<h1>sus</h1>

app/views/home/index.html.erb
<br>

<h1 class="animated zoomIn bianco">Tours Castelli della Loira</h1>

<br>

<div class="container">
    <div class="row">
        <div class="col-sm">
            <div class="animated zoomIn">
                <div class="card bg-dark text-white">
                    <img src="/images/H1.jpg" class="card-img" alt="...">
                    <div class="card-img-overlay">
                        <h5 class="card-title">Tours</h5>
                        <p class="card-text">Qui dentro troverete tutti i nostri interessantissimi tours</p>
                        <a class=""href=/tours ><button type="button" class="btn btn-dark">Scopri i tours</button></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="animated zoomIn">
                <div class="card bg-dark text-white">
                    <img src="/images/H2.jpg" class="card-img" alt="...">
                    <div class="card-img-overlay">
                        <h5 class="card-title">Newsletter</h5>
                        <p class="card-text">Iscriviti alla newsletter per rimanere sempre aggiornato</p>
                        <a class="/utentis/new"href=/tours><button type="button" class="btn btn-dark">Iscriviti</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<br>

<div class="container animated zoomIn">
    <h3 class="animated zoomIn bianco">Più informazioni sui Castelli della Loira</h1>
    <img src="/images/H3.jpg" class="w-50" alt="...">
    <br>
    <p class="bianco">La Valle della Loira (in francese: le Val de Loire) è conosciuta come il Giardino di Francia e la Culla della lingua francese. È nota anche per la qualità del suo patrimonio architettonico, per le sue città storiche come Montsoreau, Amboise, Angers, e per i suoi famosi castelli conosciuti in tutto il mondo. Il paesaggio della Valle della Loira e in particolare i suoi principali monumenti culturali illustrano a un livello eccezionale gli ideali del Rinascimento e dell'età dei lumi del pensiero e dell'ingegno europeo. La Valle della Loira è un luogo di importante bellezza dove è possibile visitare città e villaggi di rilevanza storica, splendidi monumenti architettonici, numerosi castelli e apprezzare alcuni dei migliori vini dell'intera Francia.
    </p>
</div>

<br>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/css/style.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

      <title></title>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/index">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/tours">Tours</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="/utentis/new">Newsletter</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>


      <div id="carouselExampleCaptions" class="carousel slide animated zoomIn" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="/images/c1.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h2 class="animated zoomIn">Tours Castelli della Loira</h2>
              <h4 class="animated zoomIn">I bellissimi castelli </h4>
            </div>
          </div>
          <div class="carousel-item">
            <img src="/images/c2.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h2 class="animated zoomIn">Tours Castelli della Loira</h2>
              <h4 class="animated zoomIn">lo splendido panorama</h4>
            </div>
          </div>
          <div class="carousel-item">
            <img src="/images/c3.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h2 class="animated zoomIn">Tours Castelli della Loira</h2>
              <h4 class="animated zoomIn">Il fantastico cielo</h4>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

    <%= yield %>


    <p> </p>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Castelli della Loira</h3>
                        <ul>
                            <li><a href="/tours">Esplora i tours</a></li>
                            
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Newsletter</h3>
                        <ul>
                            <li><a href="/utentis/new">iscriviti alla newsletter</a></li>
                        </ul>
                    </div>
                  
                    <div class="col-md-6 item text">
                        <h3>Castelli della Loira</h3>
                        <p>Da tante generazioni i migliori tours dei Castelli della Loira</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">i migliori tours nei Castelli della Loira © 1969</p>
            </div>
        </footer>
    </div>
  </body>
</html>

    


    

    

app/views/tours/_form.html.erb
<%= form_with(model: tour) do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
        <% tour.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

<div class="container-fluid animated zoomIn">
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label :denominazione, class: 'form-label bianco'%>
          <%= form.text_field :denominazione, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label :descrizione, class: 'form-label bianco'%>
          <%= form.text_field :descrizione, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label 'descrizione inglese', class: 'form-label bianco' %>
          <%= form.text_field :descrizioneing, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label 'luogo partenza', class: 'form-label bianco' %>
          <%= form.text_field :luogopartenza, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label 'giorni e orari partenza', class: 'form-label bianco' %>
          <%= form.text_field :giorniorarip, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label :durata, class: 'form-label bianco' %>
          <%= form.number_field :durata, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label 'partecipanti massimi', class: 'form-label bianco' %>
          <%= form.number_field :maxpartecipanti, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label :cover, class: 'form-label bianco' %>
          <%= form.file_field :cover, class: 'form-control' %>
        </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Aggiungi/modifica tour', class: 'btn btn-dark' %>
  </div>
  <br>
<% end %>

app/views/tours/edit.html.erb
<h1 class="bianco animated zoomIn">Modifica Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Mostra', @tour, class:'btn btn-dark' %> 
<%= link_to 'Indietro', tours_path, class:'btn btn-dark' %>

app/views/tours/index.html.erb
<h1 class="bianco animated zoomIn">Tours</h1>
 
<% @tours.each do |tour| %>
  <div class="container-fluid animated zoomIn">
    <div class="row">
    <div class="col-4">
    
    </div>
      <div class="col-8">
          <div class="card mb-3 bglgray" style="max-width: 540px;">
            <div class="row g-0">
              <div class="col-md-4">
                <% if tour.cover.attached? %>
                  <%= link_to (image_tag url_for(tour.cover),class: 'w-100'), tour %>
                <% end %>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title bianco"><%= tour.denominazione %></h5>
                  <p class="card-title bianco">partenza da: <%= tour.luogopartenza %></p>
                  <p class="card-title bianco">giorni e orari partenza : <%= tour.giorniorarip %></p>
                  <p class="card-title bianco">Durata: <%= tour.durata %> ore</p>
                  <p class="card-title bianco">Partecipanti massimi:<%= tour.maxpartecipanti %></p>
                  <br>
                  <%= link_to 'Modifica', edit_tour_path(tour), class:'btn btn-dark' %>
                  <%= link_to 'Cancella', tour, method: :delete, data: { confirm: 'Sei sicuro?' }, class:'btn btn-dark' %>
                </div>
              </div>
          </div>
      </div>
      <div class="col-4">

      </div>
    </div>
    </div>
  </div>
</div>
<% end %>


<br>

<%= link_to 'Nuovo Tour', new_tour_path, class:'btn btn-dark' %>

<br><br>

app/views/tours/new.html.erb
<h1 class="bianco animated zoomIn">Nuovo Tour</h1>

<%= render 'form', tour: @tour %>

<br>
<%= link_to 'Indietro', tours_path, class:'btn btn-dark' %>
<br>

app/views/tours/show.html.erb
<div class="container animated zoomIn">
  <div class="row">
    <div class="col-sm">
      <% if @tour.cover.attached? %>
        <%= image_tag url_for(@tour.cover)%>
      <% end %>
      <br>
      <h3 class="bianco"><%= @tour.denominazione %></h3>
      <p class="bianco"><%= @tour.descrizione %></p>
      <p class="bianco"><%= @tour.descrizioneing %></p>
      <h4 class="bianco">partenza da: <%= @tour.luogopartenza %></h4>
      <h4 class="bianco"><%= @tour.giorniorarip %></h4>
      <h4 class="bianco">durata: <%= @tour.durata %> ore</h4>
      <h4 class="bianco">partecipanti massimi: <%= @tour.maxpartecipanti %></h4>
    </div>
  </div>
</div>
<br>
<%= link_to 'Modifica', edit_tour_path(@tour), class:'btn btn-dark' %> 
<%= link_to 'Indietro', tours_path, class:'btn btn-dark' %>

app/views/utentis/_form.html.erb
<%= form_with(model: utenti) do |form| %>
  <% if utenti.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(utenti.errors.count, "error") %> prohibited this utenti from being saved:</h2>

      <ul>
        <% utenti.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  


<div class="container-fluid animated zoomIn">
  <div class="container">
    <div class="row">
      <div class="col-sm form-label">
        <%= form.label :cognome, class: 'form-label bianco'%>
        <%= form.text_field :cognome, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm form-label">
        <%= form.label :nome, class: 'form-label bianco'%>
        <%= form.text_field :nome, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm form-label">
        <%= form.label :indirizzo, class: 'form-label bianco'%>
        <%= form.text_field :indirizzo, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm form-label">
        <%= form.label :email, class: 'form-label bianco'%>
        <%= form.text_field :email, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm form-label">
        <%= form.label :numero, class: 'form-label bianco' %>
        <%= form.number_field :numero, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm form-label">
        <%= form.label :note, class: 'form-label bianco' %>
        <%= form.text_field :note, class: 'form-control' %>
      </div>
    </div>
  </div>
</div>

  <div class="actions">
    <%= form.submit 'Crea/modifica utente', class:'btn btn-dark' %>
  </div>

  <br>
<% end %>

app/views/utentis/edit.html.erb
<h1 class="bianco animated zoomIn">Modifica Utenti</h1>

<%= render 'form', utenti: @utenti %>

<%= link_to 'Mostra', @utenti, class:'btn btn-dark' %> |
<%= link_to 'Indietro', utentis_path, class:'btn btn-dark' %>

app/views/utentis/index.html.erb
<h1 class="bianco animated zoomIn">Utenti</h1>


<table class="table animated zoomIn">
  <thead>
    <tr>
    <th class="bianco">Cognome</th>
    <th class="bianco">Nome</th>
    <th class="bianco">Indirizzo</th>
    <th class="bianco">Email</th>
    <th class="bianco">Numero</th>
    <th class="bianco">Note</th>
    <th class="bianco"></th>
    <th class="bianco"></th>
    <th class="bianco"></th>
    </tr>
  </thead>
  <tbody>
    <% @utentis.each do |utenti| %>
      <tr>
        <td class="bianco"><%= utenti.cognome %></td>
        <td class="bianco"><%= utenti.nome %></td>
        <td class="bianco"><%= utenti.indirizzo %></td>
        <td class="bianco"><%= utenti.email %></td>
        <td class="bianco"><%= utenti.numero %></td>
        <td class="bianco"><%= utenti.note %></td>
        <td class="bianco"><%= link_to 'Mostra', utenti, class: 'btn btn-dark' %></td>
        <td class="bianco"><%= link_to 'Modifica', edit_utenti_path(utenti), class: 'btn btn-dark' %></td>
        <td class="bianco"><%= link_to 'Elimina', utenti, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-dark' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Nuovo Utente', new_utenti_path, class:'btn btn-dark' %>
<br>

app/views/utentis/new.html.erb
<h1 class="bianco animated zoomIn">Nuovo Utente</h1>

<%= render 'form', utenti: @utenti%>

<%= link_to 'Indietro', utentis_path, class:'btn btn-dark' %>

app/views/utentis/show.html.erb
<div class="animated zoomIn">
  <p class="bianco">
    <strong>Cognome:</strong>
    <%= @utenti.cognome %>
  </p>

  <p class="bianco">
    <strong>Nome:</strong>
    <%= @utenti.nome %>
  </p>

  <p class="bianco">
    <strong>Indirizzo:</strong>
    <%= @utenti.indirizzo %>
  </p>

  <p class="bianco">
    <strong>Email:</strong>
    <%= @utenti.email %>
  </p>

  <p class="bianco">
    <strong>Numero:</strong>
    <%= @utenti.numero %>
  </p>

  <p class="bianco">
    <strong>Note:</strong>
    <%= @utenti.note %>
  </p>
</div>

<%= link_to 'Modifica', edit_utenti_path(@utenti), class:'btn btn-dark' %> |
<%= link_to 'Indietro', utentis_path, class:'btn btn-dark' %>